### ISSUE TITLE
App not appearing on Apple Watch

### ISSUE THREAD

**Issue by vinodhmoodley** [Rexios80/Health-Data-Server-Overlay#1]
I purchased the app on the App Store but it doesn’t appear on the Apple Watch. There’s no iPhone app to remove so there’s uninstall option to try and fix the issue. Also, it’s not listed in the available apps section as well. I’ve removed both devices from WiFi and reconnected, I’ve restarted both devices multiple times and also disconnected Bluetooth multiple times. Other apps that I install appear on the watch without issue.

**Comment by Rexios80** [comment]
What version of watchOS are you running?

**Comment by vinodhmoodley** [comment]
watchOS 6.1.3
iOS 13.3.1

**Comment by Rexios80** [comment]
Alright so I was also unable to install the app from the App Store on my iPhone. That’s weird because I was able to do that before. However, I was able to search for it on the App Store on the watch and successfully install it from there. This is probably a problem with iOS/watchOS and not something I can fix.

**Comment by vinodhmoodley** [comment]
Thanks. I used that method and got it working. Much appreciated.

**Comment by Rexios80** [comment]
Added to the wiki as a troubleshooting step
