### ISSUE TITLE
Make a force touch on the stop button bring up a 'do you want to stop' dialog

### ISSUE THREAD

**Issue by tychopsycho** [Rexios80/Health-Data-Server-Overlay#15]
More of a suggestion than a bug, just got the app and installed it today, loving it, but it took me about 30s to manage to get the app to stop because I kept trying to hold down the stop button but the force touch would cancel. If it reacts to a force touch anyway could you make it pop up a "would you like to stop: yes/no" dialog if you force touch the stop button rather than having it cancel the stop app countdown?

**Comment by Rexios80** [comment]
The reason I implemented the stop functionality this way is Force Touch is going away in watchOS 7. I'm running the watchOS 7 developer beta and it seems pretty hard to cancel the countdown by pressing too hard, so I'm hoping this issue will go away once watchOS 7 releases. Also I don't think it's possible for me to ignore the Force Touch, since it's handled by the system.

**Comment by tychopsycho** [comment]
Ah I forgot that force touch is going away! I guess that will solve the problem, I just have to be so careful right now when cancelling.
