### ISSUE TITLE
Use app without affecting apple watch move ring

### ISSUE THREAD

**Issue by happyjunki3** [Rexios80/Health-Data-Server-Overlay#24]
Hey there. Love the app and everything is perfect except for this. How can I stop the app from adding calories to my move ring? I have "save to health" toggled off and the activity set to walking. It does not add minutes to my exercise ring, but it does seem to think I am burning calories because it registers the workout in the activity app and it fills in the red ring. I'm using the overlay just to show my BPM while gaming. Can I could disable the calorie burn completely? Or is there an activity that will register no calories burned ?

Thank you!

**Comment by Rexios80** [comment]
Ugh I've been trying to add this feature for months but I keep having problems with the HealthKit permissions. I released it on TestFlight, but it might be broken. Or it might work. Who knows. I haven't been able to test it since the permissions are broken for me.

https://testflight.apple.com/join/hG4FkmZ4

(The build isn't approved at the time I'm writing this. It should show up within a day or two.)

**Comment by happyjunki3** [comment]
feels better to know its not just me lol. i'll keep checking to see if it is approved and i'd be happy to test it out for you and give some feedback

**Comment by Rexios80** [comment]
I have submitted an update to the App Store that no longer affects the Activity Rings if "Save to Health" is turned off. It should be ready within the next few days. This update requires a new server version since I pretty much completely rewrote the backend of the watch app. I will release the watch app and new server version as soon as I can.

**Comment by happyjunki3** [comment]
You are awesome! I will be sure to let you know if it works on my end

**Comment by Rexios80** [comment]
I left it running while I slept last night and it actually recorded 0 calories or exercise minutes. I'm pretty confident it works.

**Comment by Rexios80** [comment]
Apparently the App Store review is done already. That was fast. I released the server update along side it so test away.

**Comment by happyjunki3** [comment]
You are absolutely wonderful! It works perfectly. So it took me a while to figure out that the ip address in settings doesn't need :8080 at the end anymore.. lol but once i did, the app works perfectly. turning save to health does still allow you to track your calories while using the app, but once you set it off, it does not register any calories and the overlay doesn't display calories either. it is perfect and just what I wanted so thank you a million times again! I couldn't be happier. I also left a positive review on the app store to help out. sucks that the rating is so low when the app works so well. anyway thanks again see ya!

**Comment by Rexios80** [comment]
Is there anything I can do to make the port change clearer in the release notes?

Also yeah I'm really happy I finally got the "Save to Health" thing figured out. I've been working on it since almost a year ago and just couldn't get it working no matter what I tried. I'm glad it works for you!

The reason the app has such low reviews is because there are a lot of network issues that can happen that aren't my fault but people don't know that. Also for some dumb reason the App Store on the iPhone let's you purchase the app even if you don't have watchOS 6+ which the app requires. Also you can buy the app on the iPhone but you can't install it from there and people don't understand that there is an App Store on the watch. So yeah it sucks lol.

**Comment by happyjunki3** [comment]
I gotta say i had issues installing the app on the iphone too initially lol. I did like you said.. bought it on the iphone and then i couldn’t figure out how to get it on the freaking watch. What i did was open the app store from the watch and i had to search the name exactly. It was the only way. Perhaps instructions on this should be included in the install guide as well?

For the update: the only thing i had to do was install the new exe and then go to the settings and uncheck save to health of course but also remove the :8080 from the ip address. The watch automatically updates all the apps so i didn’t have to redownload anything there. From there everything works as intended!

Also another improvement that i noticed is that the app used to disconnect after 2-3 hours randomly and i would have to reconnect. I did a 5 hour stream yesterday and it stayed connected the whole time so i was super happy :)

**Comment by Rexios80** [comment]
I added a line to the README that says the app needs to be installed from the App Store on the watch. Hopefully that helps new people.
It's weird that the app was disconnecting before, but the new communication method is more stable so I'm glad it's fixed. At least I didn't put a bunch of work into it for no benefit.

**Comment by christran** [comment]
Where is the "Save to Health" toggle? I can't seem to find it anywhere in the settings.

**Comment by Rexios80** [comment]
Where did you even see anything about that? That's like a year old. If you have calories off it won't affect your rings.

**Comment by christran** [comment]
> Where did you even see anything about that? That's like a year old. If you have calories off it won't affect your rings.

https://github.com/Rexios80/Health-Data-Server-Overlay/issues/24#issuecomment-706588054

That's why I was looking for the "Save to Health" option, didn't know I just had to turn off calories.
